version: "3.1"
services:
##################################################
#                   REDIS                        #
##################################################
    redis:
      image: redis:alpine
      container_name: redis
      restart: always
      ports:
        - "6379:6379"
      networks:
        - app-network 
##################################################
#                 PHPMYADMIN                     #
##################################################
    # phpmyadmin:
    #   image: phpmyadmin/phpmyadm
    #   container_name: phpmyadmin 
    #   restart: always
    #   ports:
    #     - "8081:80"
    #   environment:
    #     - PMA_ARBITRARY=1
    #   # links:
    #   #   - mysql
    #   networks:
    #     - app-network
    #   # depends_on:
    #   #   - "mysql"
##################################################
#                 MYSQL                          #
##################################################
    mysql:
      image: mysql:5.7
      container_name: mysql
      working_dir: /application
      restart: always
      volumes:
        - ./.docker/dbdata:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=Moderador12@
        - MYSQL_DATABASE=wacorner_bd
        - MYSQL_USER=wacorner_user
        - MYSQL_PASSWORD=Moderador12@
      ports:
        - "3306:3306"
      networks:
        - app-network
##################################################
#                 NGINX                          #
##################################################
    nginx:
      build:
        context: ./
        dockerfile: Dockerfile-nginx
      container_name: nginx
      working_dir: /application
      restart: always
      volumes:
        - ./app:/application
      ports:
       - "80:80"
      links:
       - php-fpm
      networks:
        - app-network
##################################################
#                 SUPERVISOR                     #
##################################################
    supervisor:
      build:
        context: ./
        dockerfile: Dockerfile-supervisor
      container_name: supervisor
      working_dir: /application
      volumes:
        - ./app:/application
      restart: always
      # volumes:
      #   - ./application:/application
      ports:
        - "9001:9001"
      links:
        # - mysql
        - redis
      networks:
        - app-network
      depends_on:
        # - "mysql"
        - "redis"
##################################################
#                 PHP-FPM                        #
##################################################
    php-fpm:
      build:
        context: ./
        dockerfile: Dockerfile-php-fpm
      container_name: php-fpm
      working_dir: /application
      volumes:
        - ./app:/application
      restart: always
      networks:
        - app-network
      links:
        # - mysql
        - redis
      depends_on:
        # - "mysql"
        - "redis"
##################################################
#              REDES DOCKER                      #
##################################################
networks:
  app-network:
    driver: bridge
