version: "3.4"
services:
  traefik:
    image: "traefik:v2.0.0-rc3"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.wacorner.com`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    networks:
      - traefik
    deploy:
      replicas: 2

  visualizer:
    image: dockersamples/visualizer:stable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.visualiser.rule=Host(`console.wacorner.com`)"
        - "traefik.http.routers.visualiser.entrypoints=web"
    depends_on:
      - traefik
    networks:
      - traefik
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
networks:
  traefik:
    driver: overlay

  


