version: "3.4"
services:
  traefik:
    image: "traefik:v2.0.0-rc3"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.endpoint='unix:///var/run/docker.sock'"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesResolvers.sample.acme.email="wacornerstats@gmail.com"
      - "--certificatesResolvers.sample.acme.storage='acme.json'"
      - "--certificatesResolvers.sample.acme.httpChallenge.entryPoint=web"
      - "--certificatesResolvers.sample.acme.dnsChallenge.provider=cloudflare"
      - "--certificatesResolvers.sample.acme.dnsChallenge.delayBeforeCheck=0"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certificates/acme.json:acme.json"
    networks:
      - traefik
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    labels:
      - traefik.http.routers.whoami.rule=Host(`whoami.wacorner.com`)
      - traefik.http.services.whoami-service.loadbalancer.server.port=80
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.entrypoints=web,websecure"
    networks:
      - traefik
    deploy:
      replicas: 2

  visualizer:
    image: dockersamples/visualizer:stable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
      - traefik.http.routers.visualizer.rule=Host(`console.wacorner.com`)
      - traefik.http.services.visualizer-service.loadbalancer.server.port=8080
      - "traefik.http.routers.visualizer.tls=true"
      - "traefik.http.routers.visualizer.entrypoints=web,websecure"
    depends_on:
      - traefik

networks:
  traefik:
    driver: overlay

  


