version: "3.1"
services:
##################################################
#                   REDIS                        #
##################################################
    redis:
      image: redis:alpine
      # container_name: redis
      restart: always
      ports:
        - "6379:6379"
      networks:
        - app-network 
##################################################
#                 PHPMYADMIN                     #
##################################################
    phpmyadmin:
      image: bitnami/phpmyadmin:latest
      environment:
        - PHPMYADMIN_ALLOW_ARBITRARY_SERVER=true
      ports:
        - "8081:80"
      networks:
        - app-network

##################################################
#                 MYSQL                          #
##################################################
    mysql:
      image: mysql:5.7
      # container_name: mysql
      working_dir: /var/lib/mysql
      restart: always
      volumes:
        - ./.docker/dbdata:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=Moderador12@
        - MYSQL_DATABASE=wacorner_bd
        - MYSQL_USER=wacorner_user
        - MYSQL_PASSWORD=Moderador12@
      ports:
        - "3306:3306"
      networks:
        - app-network
##################################################
#                 NGINX                          #
##################################################
    nginx:
      build:
        context: ./
        dockerfile: Dockerfile-nginx
      # container_name: nginx
      working_dir: /application
      restart: always
      command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
      volumes:
        - ./app:/application
        - ./data/certbot/conf:/etc/letsencrypt 
        - ./data/certbot/www:/var/www/certbot
      ports:
        - "80:80"
        - "443:443"
      networks:
        - app-network

    certbot:
      image: certbot/certbot
      volumes: 
        - ./data/certbot/conf:/etc/letsencrypt 
        - ./data/certbot/www:/var/www/certbot
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
##################################################
#                 SUPERVISOR                     #
##################################################
    supervisor:
      build:
        context: ./
        dockerfile: Dockerfile-supervisor
      # container_name: supervisor
      working_dir: /application
      restart: always
      volumes:
        - ./app:/application
      ports:
        - "9001:9001"
      # links:
      #   # - mysql
      #   - redis
      networks:
        - app-network
      # depends_on:
      #   # - "mysql"
      #   - "redis"
##################################################
#                 PHP-FPM                        #
##################################################
    php-fpm:
      build:
        context: ./
        dockerfile: Dockerfile-php-fpm
      # container_name: php-fpm
      working_dir: /application
      volumes:
        - ./app:/application
      restart: always
      networks:
        - app-network
      environment:
        - APP_DEBUG=true
        - LOG_SLACK_WEBHOOK_URL=https://hooks.slack.com/services/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
        - LOG_LEVEL=info
        - TELESCOPE_ENABLED=false
        - CACHE_DRIVER=redis
        - SESSION_DRIVER=file
      # links:
      #   - mysql
      #   - redis
      # depends_on:
      #   - "mysql"
      #   - "redis"
##################################################
#              REDES DOCKER                      #
##################################################
networks:
  app-network:
