version: "3.4"
services:
  redis:
      image: redis:alpine
      ports:
        - "6379:6379"
      networks:
        - traefik
      deploy:
        replicas: 1
        placement:
          constraints: 
            - node.role == manager
  phpmyadmin:
      image: phpmyadmin/phpmyadm
      ports:
        - "8081:80"
      environment:
        - PMA_ARBITRARY=1
      networks:
        - traefik
      depends_on:
        - "mysql"
      deploy:
        replicas: 1
        placement:
          constraints: 
            - node.role == worker
        labels:
            - "traefik.port=8081"
            - "traefik.frontend.rule=Host:mysql.wacorner.com"
      depends_on:
        - traefik_init
        - consul
        - mysql
        - traefik
  mysql:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      volumes:
        - ./.docker/dbdata:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=Moderador12@
        - MYSQL_DATABASE=wacorner_bd
        - MYSQL_USER=wacorner_user
        - MYSQL_PASSWORD=Moderador12@
      ports:
        - "3306:3306"
      networks:
        - traefik
      deploy:
        replicas: 1
        placement:
          constraints: 
            - node.role == manager
  # nginx:
  #     image: wesleyvieira12/wacorner-nginx:v1
  #     ports:
  #      - "8082:80"
  #     networks:
  #       - traefik
  #     deploy:
  #       replicas: 1
  #       placement:
  #         constraints: 
  #           - node.role == worker
  #       labels:
  #         - "traefik.port=8082"
  #         - "traefik.frontend.rule=Host:corner.wacorner.com"
  #         - "traefik.backend.loadbalancer.stickiness=true"
  # php-fpm:
  #     image: wesleyvieira12/wacorner-php-fpm:v1
  #     networks:
  #       - traefik
  #     ports:
  #       - "9000:9000"
  #     depends_on:
  #       - "mysql"
  #       - "redis"
  #     deploy:
  #       replicas: 1
  #       placement:
  #         constraints: 
  #           - node.role == worker
  supervisor:
      image: wesleyvieira12/wacorner-supervisor:v1
      networks:
        - traefik
      ports:
        - "9001:9001"
      deploy:
        replicas: 1
        placement:
          constraints: 
            - node.role == worker
        labels:
          - "traefik.port=9001"
          - "traefik.frontend.rule=Host:supervisor.wacorner.com"
          - "traefik.docker.network: traefik"
      depends_on:
        - traefik_init
        - traefik
        - consul
        - mysql
        - redis
  
  traefik_init:
    image: traefik:v1.7.18-alpine
    command:
      - "storeconfig"
      - "--api"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--acme"
      - "--acme.storage=traefik/acme/account"
      - "--acme.entryPoint=https"
      - "--acme.httpChallenge.entryPoint=http"
      - "--acme.onHostRule=true"
      - "--acme.onDemand=false"
      - "--acme.email=wesleyvieira12@gmail.com"
      - "--docker"
      - "--docker.swarmMode"
      - "--docker.domain=wacorner.com"
      - "--docker.watch"
      - "--consul"
      - "--consul.endpoint=consul:8500"
      - "--consul.prefix=traefik"
    networks:
      - traefik
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - consul
  
  traefik:
    image: traefik:v1.7.18-alpine
    depends_on:
      - traefik_init
      - consul
    command:
      - "--consul"
      - "--consul.endpoint=consul:8500"
      - "--consul.prefix=traefik"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - webgateway
      - traefik
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  
  consul:
    image: consul
    command: agent -server -bootstrap-expect=1
    volumes:
      - consul-data:/consul/data
    environment:
      - CONSUL_LOCAL_CONFIG={"datacenter":"us_east2","server":true}
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - traefik
  
  visualizer:
    image: dockersamples/visualizer:stable
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:console.wacorner.com"
    depends_on:
      - traefik_init
      - traefik
      - consul

networks:
  webgateway:
    driver: overlay 
  traefik:
    driver: overlay

volumes:
  consul-data:
      driver: local

  


