version: '3.3'

services:
  whoami:
    image: "containous/whoami"
    networks:
      - default
      - traefik-public
    deploy:
        replicas: 2
        placement:
          constraints: 
            - node.role == worker
        labels:
            - traefik.frontend.rule=Host:whoami.${DOMAIN?Variable DOMAIN not set}
            - traefik.enable=true
            - traefik.port=80
            - traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}
            - traefik.docker.network=traefik-public
            # Traefik service that listens to HTTP
            - traefik.redirectorservice.frontend.entryPoints=http
            - traefik.redirectorservice.frontend.redirect.entryPoint=https
            # Traefik service that listens to HTTPS
            - traefik.webservice.frontend.entryPoints=https
  visualizer:
    image: dockersamples/visualizer:stable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
            - traefik.frontend.rule=Host:visualizer.${DOMAIN?Variable DOMAIN not set}
            - traefik.enable=true
            - traefik.port=8080
            - traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}
            - traefik.docker.network=traefik-public
            # Traefik service that listens to HTTP
            - traefik.redirectorservice.frontend.entryPoints=http
            - traefik.redirectorservice.frontend.redirect.entryPoint=https
            # Traefik service that listens to HTTPS
            - traefik.webservice.frontend.entryPoints=https
    depends_on:
      - traefik
      - consul-leader
  phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      environment:
        - PMA_ARBITRARY=1
      networks:
        - default
        - traefik-public
      depends_on:
        - mysql
        - consul-leader
        - traefik
      deploy:
        replicas: 1
        placement:
          constraints: 
            - node.role == worker
        labels:
            - traefik.frontend.rule=Host:phpmyadmin.${DOMAIN?Variable DOMAIN not set}
            - traefik.enable=true
            - traefik.port=80
            - traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}
            - traefik.docker.network=traefik-public
            # Traefik service that listens to HTTP
            - traefik.redirectorservice.frontend.entryPoints=http
            - traefik.redirectorservice.frontend.redirect.entryPoint=https
            # Traefik service that listens to HTTPS
            - traefik.webservice.frontend.entryPoints=https
  mysql:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      volumes:
        - db_data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=Moderador12@
        - MYSQL_DATABASE=wacorner_bd
        - MYSQL_USER=wacorner_user
        - MYSQL_PASSWORD=Moderador12@
      ports:
        - "3306:3306"
      networks:
        - default
        - traefik-public
      depends_on:
        - consul-leader
        - traefik
      deploy:
        replicas: 1
        placement:
          constraints: 
            - node.role == manager
  consul-leader:
    image: consul
    command: agent -server -client=0.0.0.0 -bootstrap -ui
    volumes:
      - consul-data-leader:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - default
      - traefik-public
    deploy:
      labels:
        - traefik.frontend.rule=Host:consul.${DOMAIN?Variable DOMAIN not set}
        - traefik.enable=true
        - traefik.port=8500
        - traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        - traefik.frontend.auth.basic.users=${USERNAME?Variable USERNAME not set}:${HASHED_PASSWORD?Variable HASHED_PASSWORD not set}
  consul-replica:
    image: consul
    command: agent -server -client=0.0.0.0 -retry-join="consul-leader"
    volumes:
      - consul-data-replica:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - default
      - traefik-public
    deploy:
      replicas: ${CONSUL_REPLICAS:-3}
      placement:
        preferences:
          - spread: node.id
  traefik:
    image: traefik:v1.7
    ports:
      - 80:80
      - 443:443
    deploy:
      replicas: ${TRAEFIK_REPLICAS:-3}
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.id
      labels:
        - traefik.frontend.rule=Host:traefik.${DOMAIN?Variable DOMAIN not set}
        - traefik.enable=true
        - traefik.port=8080
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        - traefik.frontend.auth.basic.users=${USERNAME?Variable USERNAME not set}:${HASHED_PASSWORD?Variable HASHED_PASSWORD not set}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      --docker
      --docker.swarmmode
      --docker.watch
      --docker.exposedbydefault=false
      --constraints=tag==traefik-public
      --entrypoints='Name:http Address::80'
      --entrypoints='Name:https Address::443 TLS'
      --consul
      --consul.endpoint="consul-leader:8500"
      --acme
      --acme.email=${EMAIL?Variable EMAIL not set}
      --acme.storage="traefik/acme/account"
      --acme.entryPoint=https
      --acme.httpChallenge.entryPoint=http
      --acme.onhostrule=true
      --acme.acmelogging=true
      --logLevel=INFO
      --accessLog
      --api
    networks:
      - default
      - traefik-public
    depends_on:
      - consul-leader
        
volumes:
  consul-data-leader:
  consul-data-replica:
  db_data:

networks:
  traefik-public:
    external: true
  default:
    attachable: true
