version: '3.3'

services:
  redis:
      image: redis:alpine
      networks:
        - default
        - traefik-public
      depends_on:
        - consul-leader
        - traefik
      ports:
        - "6379:6379"
      deploy:
        replicas: 1
        placement:
          constraints: 
            - node.role == manager
  supervisor:
    image: wesleyvieira12/wacorner-supervisor:v4
    networks:
      - default
      - traefik-public
    deploy:
        replicas: 1
        labels:
            - traefik.frontend.rule=Host:supervisor.wacorner.com
            - traefik.enable=true
            - traefik.port=9001
            - traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}
            - traefik.docker.network=traefik-public
            # Traefik service that listens to HTTP
            - traefik.redirectorservice.frontend.entryPoints=http
            - traefik.redirectorservice.frontend.redirect.entryPoint=https
            # Traefik service that listens to HTTPS
            - traefik.webservice.frontend.entryPoints=https
    depends_on:
      - traefik
      - consul-leader
      - mysql
  php-fpm:
    image: wesleyvieira12/wacorner-php-fpm:v3
    networks:
      - default
      - traefik-public
    deploy:
        replicas: 3
        # placement:
        #   constraints: 
        #     - node.role == worker
    depends_on:
      - traefik
      - consul-leader
      - mysql
  nginx:
    image: wesleyvieira12/wacorner-nginx:v1
    networks:
      - default
      - traefik-public
    deploy:
        replicas: 3
        # placement:
        #   constraints: 
        #     - node.role == worker
        labels:
            - traefik.frontend.rule=Host:wacorner.com
            - traefik.enable=true
            - traefik.port=80
            - traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}
            - traefik.docker.network=traefik-public
            # Traefik service that listens to HTTP
            - traefik.redirectorservice.frontend.entryPoints=http
            - traefik.redirectorservice.frontend.redirect.entryPoint=https
            # Traefik service that listens to HTTPS
            - traefik.webservice.frontend.entryPoints=https
    depends_on:
      - traefik
      - consul-leader
      - php-fpm
      - mysql
  visualizer:
    image: dockersamples/visualizer:stable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
            - traefik.frontend.rule=Host:visualizer.wacorner.com
            - traefik.enable=true
            - traefik.port=8080
            - traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}
            - traefik.docker.network=traefik-public
            # Traefik service that listens to HTTP
            - traefik.redirectorservice.frontend.entryPoints=http
            - traefik.redirectorservice.frontend.redirect.entryPoint=https
            # Traefik service that listens to HTTPS
            - traefik.webservice.frontend.entryPoints=https
    depends_on:
      - traefik
      - consul-leader
  phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      environment:
        - PMA_ARBITRARY=1
      networks:
        - default
        - traefik-public
      depends_on:
        - mysql
        - consul-leader
        - traefik
      deploy:
        replicas: 1
        # placement:
        #   constraints: 
        #     - node.role == worker
        labels:
            - traefik.frontend.rule=Host:phpmyadmin.wacorner.com
            - traefik.enable=true
            - traefik.port=80
            - traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}
            - traefik.docker.network=traefik-public
            # Traefik service that listens to HTTP
            - traefik.redirectorservice.frontend.entryPoints=http
            - traefik.redirectorservice.frontend.redirect.entryPoint=https
            # Traefik service that listens to HTTPS
            - traefik.webservice.frontend.entryPoints=https
  mysql:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      volumes:
        - db_data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=Moderador12@
        - MYSQL_DATABASE=wacorner_bd
        - MYSQL_USER=wacorner_user
        - MYSQL_PASSWORD=Moderador12@
      ports:
        - "3306:3306"
      networks:
        - default
        - traefik-public
      depends_on:
        - consul-leader
        - traefik
      deploy:
        replicas: 1
        placement:
          constraints: 
            - node.role == manager
  consul-leader:
    image: consul
    command: agent -server -client=0.0.0.0 -bootstrap -ui
    volumes:
      - consul-data-leader:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - default
      - traefik-public
    deploy:
      labels:
        - traefik.frontend.rule=Host:consul.wacorner.com
        - traefik.enable=true
        - traefik.port=8500
        - traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        - traefik.frontend.auth.basic.users=root:$apr1$TGnfXVRQ$PUntYRH4veA49R4EqInV8/
  consul-replica:
    image: consul
    command: agent -server -client=0.0.0.0 -retry-join="consul-leader"
    volumes:
      - consul-data-replica:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - default
      - traefik-public
    deploy:
      replicas: 3
      placement:
        preferences:
          - spread: node.id
  traefik:
    image: traefik:v1.7
    ports:
      - 80:80
      - 443:443
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.id
      labels:
        - traefik.frontend.rule=Host:traefik.wacorner.com
        - traefik.enable=true
        - traefik.port=8080
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        - traefik.frontend.auth.basic.users=root:$apr1$TGnfXVRQ$PUntYRH4veA49R4EqInV8/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      --docker
      --docker.swarmmode
      --docker.watch
      --docker.exposedbydefault=false
      --constraints=tag==traefik-public
      --entrypoints='Name:http Address::80'
      --entrypoints='Name:https Address::443 TLS'
      --consul
      --consul.endpoint="consul-leader:8500"
      --acme
      --acme.email=wesleyvieira12@gmail.com
      --acme.storage="traefik/acme/account"
      --acme.entryPoint=https
      --acme.httpChallenge.entryPoint=http
      --acme.onhostrule=true
      --acme.acmelogging=true
      --logLevel=INFO
      --accessLog
      --api
    networks:
      - default
      - traefik-public
    depends_on:
      - consul-leader
        
volumes:
  consul-data-leader:
  consul-data-replica:
  db_data:

networks:
  traefik-public:
    external: true
  default:
    attachable: true
