version: '3'
services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wacorner_bd
      MYSQL_PASSWORD: root
      MYSQL_USER: wacorner

      